# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import schedule_pb2 as schedule__pb2

GRPC_GENERATED_VERSION = '1.75.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in schedule_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ScheduleStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetJson = channel.unary_stream(
                '/Schedule/GetJson',
                request_serializer=schedule__pb2.UserId.SerializeToString,
                response_deserializer=schedule__pb2.ScheduleData.FromString,
                _registered_method=True)
        self.GetMoviesByDate = channel.unary_unary(
                '/Schedule/GetMoviesByDate',
                request_serializer=schedule__pb2.GetMoviesByDateRequest.SerializeToString,
                response_deserializer=schedule__pb2.ScheduleData.FromString,
                _registered_method=True)
        self.GetScheduleByMovie = channel.unary_unary(
                '/Schedule/GetScheduleByMovie',
                request_serializer=schedule__pb2.GetScheduleByMovieRequest.SerializeToString,
                response_deserializer=schedule__pb2.DateData.FromString,
                _registered_method=True)
        self.AddSchedule = channel.unary_unary(
                '/Schedule/AddSchedule',
                request_serializer=schedule__pb2.AddScheduleRequest.SerializeToString,
                response_deserializer=schedule__pb2.ScheduleData.FromString,
                _registered_method=True)
        self.AddMovieToDate = channel.unary_unary(
                '/Schedule/AddMovieToDate',
                request_serializer=schedule__pb2.AddScheduleRequest.SerializeToString,
                response_deserializer=schedule__pb2.ScheduleData.FromString,
                _registered_method=True)
        self.DeleteDate = channel.unary_unary(
                '/Schedule/DeleteDate',
                request_serializer=schedule__pb2.AddScheduleRequest.SerializeToString,
                response_deserializer=schedule__pb2.Empty.FromString,
                _registered_method=True)
        self.DeleteMovieFromDate = channel.unary_unary(
                '/Schedule/DeleteMovieFromDate',
                request_serializer=schedule__pb2.AddScheduleRequest.SerializeToString,
                response_deserializer=schedule__pb2.Empty.FromString,
                _registered_method=True)


class ScheduleServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetJson(self, request, context):
        """Lecture
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMoviesByDate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetScheduleByMovie(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddSchedule(self, request, context):
        """Ajout
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddMovieToDate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteDate(self, request, context):
        """Suppression
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteMovieFromDate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ScheduleServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetJson': grpc.unary_stream_rpc_method_handler(
                    servicer.GetJson,
                    request_deserializer=schedule__pb2.UserId.FromString,
                    response_serializer=schedule__pb2.ScheduleData.SerializeToString,
            ),
            'GetMoviesByDate': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMoviesByDate,
                    request_deserializer=schedule__pb2.GetMoviesByDateRequest.FromString,
                    response_serializer=schedule__pb2.ScheduleData.SerializeToString,
            ),
            'GetScheduleByMovie': grpc.unary_unary_rpc_method_handler(
                    servicer.GetScheduleByMovie,
                    request_deserializer=schedule__pb2.GetScheduleByMovieRequest.FromString,
                    response_serializer=schedule__pb2.DateData.SerializeToString,
            ),
            'AddSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.AddSchedule,
                    request_deserializer=schedule__pb2.AddScheduleRequest.FromString,
                    response_serializer=schedule__pb2.ScheduleData.SerializeToString,
            ),
            'AddMovieToDate': grpc.unary_unary_rpc_method_handler(
                    servicer.AddMovieToDate,
                    request_deserializer=schedule__pb2.AddScheduleRequest.FromString,
                    response_serializer=schedule__pb2.ScheduleData.SerializeToString,
            ),
            'DeleteDate': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteDate,
                    request_deserializer=schedule__pb2.AddScheduleRequest.FromString,
                    response_serializer=schedule__pb2.Empty.SerializeToString,
            ),
            'DeleteMovieFromDate': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteMovieFromDate,
                    request_deserializer=schedule__pb2.AddScheduleRequest.FromString,
                    response_serializer=schedule__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Schedule', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Schedule', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Schedule(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetJson(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/Schedule/GetJson',
            schedule__pb2.UserId.SerializeToString,
            schedule__pb2.ScheduleData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMoviesByDate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Schedule/GetMoviesByDate',
            schedule__pb2.GetMoviesByDateRequest.SerializeToString,
            schedule__pb2.ScheduleData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetScheduleByMovie(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Schedule/GetScheduleByMovie',
            schedule__pb2.GetScheduleByMovieRequest.SerializeToString,
            schedule__pb2.DateData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Schedule/AddSchedule',
            schedule__pb2.AddScheduleRequest.SerializeToString,
            schedule__pb2.ScheduleData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddMovieToDate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Schedule/AddMovieToDate',
            schedule__pb2.AddScheduleRequest.SerializeToString,
            schedule__pb2.ScheduleData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteDate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Schedule/DeleteDate',
            schedule__pb2.AddScheduleRequest.SerializeToString,
            schedule__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteMovieFromDate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Schedule/DeleteMovieFromDate',
            schedule__pb2.AddScheduleRequest.SerializeToString,
            schedule__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
