# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: schedule.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'schedule.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eschedule.proto\"\x18\n\x06UserId\x12\x0e\n\x06userId\x18\x01 \x01(\t\"6\n\x16GetMoviesByDateRequest\x12\x0e\n\x06userId\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\t\"<\n\x19GetScheduleByMovieRequest\x12\x0e\n\x06userId\x18\x01 \x01(\t\x12\x0f\n\x07movieId\x18\x02 \x01(\t\"D\n\x12\x41\x64\x64ScheduleRequest\x12\x0e\n\x06userId\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\t\x12\x10\n\x08moviesId\x18\x03 \x03(\t\"8\n\x0cScheduleData\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x1a\n\x06movies\x18\x02 \x03(\x0b\x32\n.MovieData\"H\n\tMovieData\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0e\n\x06rating\x18\x02 \x01(\x02\x12\x10\n\x08\x64irector\x18\x03 \x01(\t\x12\n\n\x02id\x18\x04 \x01(\t\"\x19\n\x08\x44\x61teData\x12\r\n\x05\x64\x61tes\x18\x01 \x03(\t\"\x07\n\x05\x45mpty2\xef\x02\n\x08Schedule\x12#\n\x07GetJson\x12\x07.UserId\x1a\r.ScheduleData0\x01\x12\x39\n\x0fGetMoviesByDate\x12\x17.GetMoviesByDateRequest\x1a\r.ScheduleData\x12;\n\x12GetScheduleByMovie\x12\x1a.GetScheduleByMovieRequest\x1a\t.DateData\x12\x31\n\x0b\x41\x64\x64Schedule\x12\x13.AddScheduleRequest\x1a\r.ScheduleData\x12\x34\n\x0e\x41\x64\x64MovieToDate\x12\x13.AddScheduleRequest\x1a\r.ScheduleData\x12)\n\nDeleteDate\x12\x13.AddScheduleRequest\x1a\x06.Empty\x12\x32\n\x13\x44\x65leteMovieFromDate\x12\x13.AddScheduleRequest\x1a\x06.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'schedule_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERID']._serialized_start=18
  _globals['_USERID']._serialized_end=42
  _globals['_GETMOVIESBYDATEREQUEST']._serialized_start=44
  _globals['_GETMOVIESBYDATEREQUEST']._serialized_end=98
  _globals['_GETSCHEDULEBYMOVIEREQUEST']._serialized_start=100
  _globals['_GETSCHEDULEBYMOVIEREQUEST']._serialized_end=160
  _globals['_ADDSCHEDULEREQUEST']._serialized_start=162
  _globals['_ADDSCHEDULEREQUEST']._serialized_end=230
  _globals['_SCHEDULEDATA']._serialized_start=232
  _globals['_SCHEDULEDATA']._serialized_end=288
  _globals['_MOVIEDATA']._serialized_start=290
  _globals['_MOVIEDATA']._serialized_end=362
  _globals['_DATEDATA']._serialized_start=364
  _globals['_DATEDATA']._serialized_end=389
  _globals['_EMPTY']._serialized_start=391
  _globals['_EMPTY']._serialized_end=398
  _globals['_SCHEDULE']._serialized_start=401
  _globals['_SCHEDULE']._serialized_end=768
# @@protoc_insertion_point(module_scope)
